Resources:
  # Local Resource
  ParentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "my-parent-owned-bucket-unique-123"

  # Nested Stack Resource
  MyNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ciarang-bucket-0909042025.s3.eu-west-2.amazonaws.com/bucket-template2.yaml
      Parameters:
        NestedBucketName: !Sub "ciaran-grant-nested-bucket-${AWS::AccountId}"
